use std::sync::Arc;

use chrono::{DateTime, Utc};
use ulid::Ulid;

use crate::metrics::{MetricSetKey, Value};

/// Output Message generated by this tracing layer
#[derive(serde::Serialize, Debug, Clone)]
pub enum Message {
    Metric {
        #[serde(serialize_with = "serialize_to_rfc3339_opts")]
        timestamp: DateTime<Utc>,
        run_id: Ulid,
        #[serde(serialize_with = "arc_str_serialize")]
        scenario_name: Arc<str>,
        executor_id: usize,
        metric_set_key: MetricSetKey,
        metric_value: Value,
    },
    ExecutorUpdate {
        #[serde(serialize_with = "serialize_to_rfc3339_opts")]
        timestamp: DateTime<Utc>,
        run_id: Ulid,
        #[serde(serialize_with = "arc_str_serialize")]
        scenario_name: Arc<str>,
        executor_id: usize,
        users: u64,
        stage: usize,
        #[serde(serialize_with = "serialize_to_rfc3339_opts")]
        stage_start_time: DateTime<Utc>,
    },
    Error {
        #[serde(serialize_with = "serialize_to_rfc3339_opts")]
        timestamp: DateTime<Utc>,
        err: String,
    },
    TerminatedError {
        #[serde(serialize_with = "serialize_to_rfc3339_opts")]
        timestamp: DateTime<Utc>,
        err: String,
    },
    ScenarioStarted {
        #[serde(serialize_with = "serialize_to_rfc3339_opts")]
        timestamp: DateTime<Utc>,
        run_id: Ulid,
        #[serde(serialize_with = "serialize_to_rfc3339_opts")]
        start_time: DateTime<Utc>,
        #[serde(serialize_with = "arc_str_serialize")]
        scenario_name: Arc<str>,
    },
    ScenarioEnded {
        #[serde(serialize_with = "serialize_to_rfc3339_opts")]
        timestamp: DateTime<Utc>,
        run_id: Ulid,
        #[serde(serialize_with = "arc_str_serialize")]
        scenario_name: Arc<str>,
        #[serde(serialize_with = "serialize_to_rfc3339_opts")]
        end_time: DateTime<Utc>,
    },
    ExecutorStart {
        #[serde(serialize_with = "serialize_to_rfc3339_opts")]
        timestamp: DateTime<Utc>,
        run_id: Ulid,
        #[serde(serialize_with = "arc_str_serialize")]
        scenario_name: Arc<str>,
        id: usize,
        #[serde(serialize_with = "serialize_to_rfc3339_opts")]
        start_time: DateTime<Utc>,
    },
    ExecutorEnd {
        #[serde(serialize_with = "serialize_to_rfc3339_opts")]
        timestamp: DateTime<Utc>,
        run_id: Ulid,
        #[serde(serialize_with = "arc_str_serialize")]
        scenario_name: Arc<str>,
        id: usize,
        #[serde(serialize_with = "serialize_to_rfc3339_opts")]
        end_time: DateTime<Utc>,
    },
}

impl Message {
    pub(crate) fn timestamp(&self) -> DateTime<Utc> {
        match self {
            Message::Metric { timestamp, .. } => *timestamp,
            Message::ExecutorUpdate { timestamp, .. } => *timestamp,
            Message::Error { timestamp, .. } => *timestamp,
            Message::TerminatedError { timestamp, .. } => *timestamp,
            Message::ScenarioStarted { timestamp, .. } => *timestamp,
            Message::ScenarioEnded { timestamp, .. } => *timestamp,
            Message::ExecutorStart { timestamp, .. } => *timestamp,
            Message::ExecutorEnd { timestamp, .. } => *timestamp,
        }
    }
}

pub fn serialize_to_rfc3339_opts<S: serde::Serializer>(
    t: &DateTime<Utc>,
    s: S,
) -> Result<S::Ok, S::Error> {
    serde::Serialize::serialize(&t.to_rfc3339_opts(chrono::SecondsFormat::Millis, false), s)
}

pub fn arc_str_serialize<S: serde::Serializer>(s: &Arc<str>, ser: S) -> Result<S::Ok, S::Error> {
    serde::Serialize::serialize(&s.as_ref(), ser)
}
